import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats 
{
	public static void main (String[] args) 
	{
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		int i;
		int twoKids = 0;
		int threeKids = 0;
		int fourKids = 0;
		int sumKids = 0;
		double totallSum = 0;
		boolean isBoy = false;
		boolean isGirl = false;
		int max;
		Random generator = new Random(seed);
		double kid;
		for (i = 0; i < T; i++)
		{
			while (!isGirl || !isBoy)
			{
				kid = generator.nextDouble();
				if (kid >= 0.5)
				{
					isGirl = true;
				}
				else
				{
					isBoy = true;
				}
				sumKids++;
				totallSum++;
			}
			if (sumKids == 2)
				twoKids++;
			if (sumKids == 3)
				threeKids++;
			if (sumKids >= 4)
				fourKids++;
			isBoy = false;
			isGirl = false;
			sumKids = 0;
		}
		System.out.println("Average: " + (totallSum / T) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + twoKids);
		System.out.println("Number of families with 3 children: " + threeKids);
		System.out.println("Number of families with 4 or more children: " + fourKids);
		max = Math.max(Math.max(twoKids, threeKids), fourKids);
		if (max == twoKids)
			System.out.println("The most common number of children is 2.");
		else
		{
			if (max == threeKids)
				System.out.println("The most common number of children is 3.");
			else
			{
				if (max == fourKids)
					System.out.println("The most common number of children is 4 or more.");
			}
		}
		    
	}
}

		//// double rnd = generator.nextDouble();